require 'hoe'
require './lib/slideshow/version.rb'

Hoe.spec 'slideshow-models' do

  self.version = Slideshow::VERSION

  self.summary = "slideshow-models - slide show (S9) models 'n' machinery for easy (re)use"
  self.description = summary

  self.urls     = ['https://github.com/slideshow-s9/slideshow']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  self.extra_deps = [
    ['props',               '>= 1.2.0'],
    ['logutils',            '>= 0.6.1'],
    ['kramdown',            '>= 2.1.0'],
    ['kramdown-parser-gfm', '>= 1.0.1'],
    ['textutils',           '>= 1.4.0'],
    ['pakman',              '>= 1.1.0'],
    ['activesupport'],
  ]

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'CHANGELOG.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 2.3'
  }

end
