require 'hoe'
require './lib/slideshow/templates/version.rb'

Hoe.spec 'slideshow-templates' do

  self.version = SlideshowTemplates::VERSION

  self.summary = "slideshow-templates - bundles builtin slide show (S9) templates 'n' snippets"
  self.description = summary

  self.urls     = ['https://github.com/slideshow-s9/slideshow-templates']

  self.author  = 'Gerald Bauer'
  self.email   = 'wwwmake@googlegroups.com'

  # switch extension to .markdown for gihub formatting
  self.readme_file  = 'README.md'
  self.history_file = 'HISTORY.md'

  self.licenses = ['Public Domain']

  self.spec_extras = {
    required_ruby_version: '>= 1.9.2'
  }

end
